# Generated by Django 2.2.7 on 2019-12-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField('Created', auto_now_add=True)),
                ('update_at', models.DateTimeField('Updated', auto_now=True)),
                ('cards', models.CharField(max_length=200)),
                ('bids', models.CharField(max_length=300)),
                ('correct_answer', models.CharField(max_length=300)),
            ],
        ),
    ]
