# Generated by Django 4.2.3 on 2024-12-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hands", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hand",
            name="explanation",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="hand",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hand",
            name="optional_bids",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="hand",
            name="user_updated",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
