# Generated by Django 4.2.3 on 2024-12-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hands", "0002_hand_explanation_hand_metadata_hand_optional_bids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hand",
            name="ew_vul",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hand",
            name="ns_vul",
            field=models.BooleanField(default=False),
        ),
    ]
