# Generated by Django 5.1.4 on 2025-01-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hands', '0003_hand_ew_vul_hand_ns_vul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='bids',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hand',
            name='cards',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='hand',
            name='explanation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
