# Generated by Django 5.1.4 on 2025-01-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hands', '0004_alter_hand_bids_alter_hand_cards_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_input', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hands', models.ManyToManyField(related_name='competitions', to='hands.hand')),
            ],
        ),
    ]
