# Generated by Django 5.1.4 on 2025-01-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hands', '0005_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
