# Generated by Django 5.1.5 on 2025-01-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('n_cards_s', models.CharField(max_length=30)),
                ('n_cards_h', models.CharField(max_length=30)),
                ('n_cards_d', models.CharField(max_length=30)),
                ('n_cards_c', models.CharField(max_length=30)),
                ('e_cards_s', models.CharField(max_length=30)),
                ('e_cards_h', models.CharField(max_length=30)),
                ('e_cards_d', models.CharField(max_length=30)),
                ('e_cards_c', models.CharField(max_length=30)),
                ('s_cards_s', models.CharField(max_length=30)),
                ('s_cards_h', models.CharField(max_length=30)),
                ('s_cards_d', models.CharField(max_length=30)),
                ('s_cards_c', models.CharField(max_length=30)),
                ('w_cards_s', models.CharField(max_length=30)),
                ('w_cards_h', models.CharField(max_length=30)),
                ('w_cards_d', models.CharField(max_length=30)),
                ('w_cards_c', models.CharField(max_length=30)),
                ('ns_vul', models.BooleanField(default=False)),
                ('ew_vul', models.BooleanField(default=False)),
                ('dealer', models.CharField(max_length=10)),
                ('bids', models.JSONField(blank=True, default=dict)),
                ('round_1', models.JSONField(blank=True, default=dict)),
                ('round_2', models.JSONField(blank=True, default=dict)),
                ('round_3', models.JSONField(blank=True, default=dict)),
                ('round_4', models.JSONField(blank=True, default=dict)),
                ('round_5', models.JSONField(blank=True, default=dict)),
                ('round_6', models.JSONField(blank=True, default=dict)),
                ('round_7', models.JSONField(blank=True, default=dict)),
                ('round_8', models.JSONField(blank=True, default=dict)),
                ('round_9', models.JSONField(blank=True, default=dict)),
                ('round_10', models.JSONField(blank=True, default=dict)),
                ('round_11', models.JSONField(blank=True, default=dict)),
                ('round_12', models.JSONField(blank=True, default=dict)),
                ('round_13', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('explanation', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
