# Generated by Django 5.1.5 on 2025-01-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
