# Generated by Django 5.1.5 on 2025-01-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='bids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
